### ISSUE TITLE
Add/remove multiple labels

### ISSUE THREAD

**Issue by mondeja** [buildsville/add-remove-label#2]
Thank you for this simple action.

Would it be possible to implement the addition and removal of multiple labels or is it something that you don't plan to add?

**Comment by buildsville** [comment]
Thanks for posting 😀 
I'm ready for this issue, but you don't need it anymore?

**Comment by mondeja** [comment]
Thank you for offering to complete the job, but I've created [an action](https://github.com/mondeja/remove-labels-gh-action) which remove labels, so I don't need it anymore.
