### ISSUE TITLE
Deprecation warning due to Node 16

### ISSUE THREAD

**Issue by Piedone** [buildsville/add-remove-label#7]
Node 16 is [now deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Because of this, when using this action, you'll see warnings.

Please update the action to Node 20.

**Comment by buildsville** [comment]
Hi, Piedone!
Thanks for report 😀 

Now, I update dependencies and released v2.0.1
Please use it.

Thank you 👍

**Comment by Piedone** [comment]
Great, thank you! Can this issue be closed, then?

**Comment by buildsville** [comment]
OK, I'll do it 🥳

**Comment by Piedone** [comment]
Thanks!
